# Generated by Django 5.2.8 on 2025-12-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ghl_contact_id',
            field=models.CharField(blank=True, help_text='GoHighLevel contact ID', max_length=255, null=True),
        ),
    ]
