# Generated by Django 5.2.8 on 2025-12-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_userprofile_ghl_contact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pincodes',
            field=models.JSONField(blank=True, default=list, help_text='List of pincodes'),
        ),
    ]
