# Generated by Django 5.2.8 on 2025-12-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_userprofile_pincodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Wallet balance', max_digits=10),
        ),
    ]
