# Generated by Django 5.2.8 on 2025-12-04 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(help_text='Job that was rejected', on_delete=django.db.models.deletion.CASCADE, related_name='rejections', to='user_app.job')),
                ('user', models.ForeignKey(help_text='User who rejected the job', on_delete=django.db.models.deletion.CASCADE, related_name='rejected_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Rejection',
                'verbose_name_plural': 'Job Rejections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'job'], name='user_app_jo_user_id_c3ca55_idx')],
                'unique_together': {('job', 'user')},
            },
        ),
    ]
