# Generated by Django 5.2.8 on 2025-12-04 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_jobrejection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='address1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='contact_id',
            field=models.CharField(blank=True, help_text='GHL Contact ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Postal code for matching with user pincodes', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='service_area',
            field=models.CharField(blank=True, help_text='Service Area from webhook', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='service_industry',
            field=models.ForeignKey(blank=True, help_text='Matching service industry for this job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='user_app.serviceindustry'),
        ),
        migrations.AddField(
            model_name='job',
            name='service_needed',
            field=models.CharField(blank=True, help_text='Service Needed from webhook', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='service_request_message',
            field=models.TextField(blank=True, help_text='Service Request Message', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(help_text='Name of the job (Service Needed)', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price for this job (from matching service industry)', max_digits=10),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['service_area', 'service_needed', 'postal_code'], name='user_app_jo_service_d1894b_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['postal_code'], name='user_app_jo_postal__81cbaa_idx'),
        ),
    ]
